# -*- coding: utf-8 -*-
"""exercícios1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wglxGCb9dSgJ69NzZrFiGnSVO9VeAJTY
"""

#Cálculo de IMC e quantidade de água recomendada
nome = input("Digite seu nome: ")
numero = float(input("Digite seu número do WhatsApp: "))
peso = float(input("Digite seu peso (em kg): "))
altura = float(input("Digite sua altura (em metros): "))

if altura > 0:
    imc = peso / (altura ** 2)
else:
    imc = 0
    print("Altura inválida. A altura deve ser maior que zero.")

agua_recomendada = peso * 35
print('---------------RESULTADO-------------')
print(f"Nome: {nome}")
print(f"WhatsApp: {numero:.0f}")
print(f"Peso: {peso} kg")
print(f"Altura: {altura} m")
if imc > 0:
    print(f"IMC: {imc:.2f}")
print(f"Quantidade de água recomendada por dia: {agua_recomendada:.2f} ml")

#Exercício 1: Par ou ímpar (if/else) Peça um número ao usuário e verifique se é par ou ímpar usando if/else
num = int(input('Digite um número para saber se é ímpar ou par: '))
if num % 2 == 0:
  print(f'O número {num} é par!')
else:
  print(f'O número {num} é ímpar!')

#Exercício 2: Classificação de idade (if/elif/else) Peça a idade de uma pessoa e classifique como Criança, Adolescente ou Adulto.
idade = int(input('Digite sua idade: '))
if idade <= 12:
  print('Você é uma criança!')
elif idade >= 13 and idade <= 17:
  print('Você é um adolescente!')
elif idade >= 18 and idade <= 25:
  print('Você é um jovem adulto')
else:
  print('Você é um adulto!')

#Exercício 3: Contagem com for Mostre os números de 1 a 5 utilizando um laço for.
numero = [1,2,3,4,5]
#da lista números, em ordem
for numero in numero:
  print(numero)

#Exercício 4: Tabuada com for Peça um número e mostre sua tabuada de 1 a 10 usando for
numero = int(input('Digite um número para descobrir sua tabuada: '))
#definir a quantidade de números para multiplicar
# o I vai contar a quantidade de algarismos dentro da lista
for i in range(1,11):
  print(f'{numero} x {i} = {numero*1}')

#Exercício 5: Contagem regressiva com while Faça um programa que realize uma contagem regressiva de 5 até 1 usando while.
print ('==========Contagem regressiva iniciada==========')
numero = 5
while numero >0:
  print(numero)
  numero -= 1
print('==========Contagem regressiva finalizada==========')

#Maneira simplificada
for i in range(1,6):
  print(i)

#Exercício 6: Função soma de dois números Crie uma função que receba dois números e retorne a soma deles.
num1 = float(input('Digite o primeiro número: '))
num2 = float(input('Digite o segundo número: '))

def soma (num1,num2):
  return num1 + num2

print(f'A soma de {num1} + {num2} = {soma(num1,num2)}')

#Exercício 7: Verificação de vogais (função de string) Peça uma letra e verifique se é uma vogal usando funções de string.
letra = str(input('Digite uma letra: ')).lower()
if letra in 'aeiou':
  print(f'A letra {letra} é uma vogal!')
else:
  print(f'A letra {letra} é uma consoante')

#Exercício 8: Contar caracteres em uma string Mostre a quantidade de caracteres de uma frase usando len().
frase = str(input('Digite uma frase: '))
print(f'A frase possui {len(frase)} caracteres')

#Exercício 9: Converta uma frase digitada pelo usuário para letras maiúsculas.
frase = str(input('Digite uma frase: '))
print(frase.upper())

#Exercício 10: Maior de três números (if/elif/else) Leia três números e mostre qual é o maior.
num1 = float(input('Digite o primeiro número: '))
num2 = float(input('Digite o segundo número: '))
num3 = float(input('Digite o terceiro número: '))

if num1 >= num2 and num1 >= num3:
  print(f'O número {num1} é o maior da sequência!')
elif num2 >= num1 and num2 >= num3:
  print(f'O número {num2} é o maior da sequência!')
else:
  print(f'O número {num3} é o maior da sequência!')

#Exercício 11: Cálculo de média e aprovação Peça duas notas, calcule a média e informe se o aluno está Aprovado, em Recuperação ou Reprovado.
n1 = float(input('Digite a primeira nota: '))
n2 = float(input('Digite a segunda nota: '))
n3 = float(input('Digite a terceira nota: '))

def calcular_media(n1,n2,n3):
  return(n1+n2+n3)/3

media = calcular_media(n1,n2,n3)
print(f'A sua média foi : {media :.2f}')

#Exercício 12: Soma dos números de 1 a 100 (for) Some todos os números de 1 a 100 usando for
soma = 0
for i in range(1, 101):
  soma += i
print(f'A soma dos números de 1 a 100 é: {soma}')

#Exercício 13: Números pares até 20 (while) Mostre todos os números pares de 2 até 20 usando while
numero = 2
while numero <= 20:
  print(numero)
  numero += 2

#Exercício 14: Função para verificar número primo Crie uma função que receba um número e retorne se ele é primo. ()
numero = int(input("Digite um número: "))
primo = True

if numero <= 1:
    primo = False
else:
    for i in range(2, numero):
        if numero % i == 0:
            primo = False
            break

if primo:
    print("É primo.")
else:
    print("Não é primo.")

#Exercício 15: Função para calcular fatorial Crie uma função que calcule o fatorial de um número.
def fatorial(n):
    resultado = 1
    for i in range(2, n + 1):
        resultado *= i
    return resultado
print(fatorial(5))

#Exercício 16: Contar palavras em uma frase (função de string) Peça uma frase e mostre quantas palavras ela possui.
frase = input("Digite uma frase: ")
quantidade_palavras = len(frase.split())
print(f"A frase tem {quantidade_palavras} palavras.")

#Exercício 17: Palíndromo (string invertida) Crie uma função que verifique se uma palavra é um palíndromo.
def palindromo(palavra):
    palavra = palavra.lower().replace(" ", "")
    return palavra == palavra[::-1]

print(palindromo("arara"))     # True
print(palindromo("python"))    # False

#Exercício 18: Substituir palavras em frase Peça uma frase e substitua uma palavra específica por outra
frase = input("Digite uma frase: ")
palavra_antiga = input("Qual palavra deseja substituir? ")
nova_palavra = input("Por qual palavra deseja substituir? ")

nova_frase = frase.replace(palavra_antiga, nova_palavra)
print("Frase atualizada:", nova_frase)
